### PR TITLE
Updated Docs

### PR DESCRIPTION
**Pull request by aeoranday**
I've made a table of the available channel maps so they may be referenced by other users. As a cross-check, I also included a command that will return the channel map names which should be built.

This does not guarantee the validity of the channel maps; it is only to show the channel maps which are available to use.

### CODE REVIEW

**Review by MRiganSUSX — COMMENTED** [review]
Thanks @aeoranday for this, very useful.

2 comments:
- since you are mentioning the readout unit in `Vertical Drift Coldbox (1 CRP)` it's also worth saying `Horizontal Drift Coldbox (1 APA)`
- (this is not something you've changed) in https://github.com/DUNE-DAQ/detchannelmaps/blob/develop/test/plugins/DummyChannelMap.cpp#L52 the parameter `offchannel` is unused.

**Comment by aeoranday** [comment]
@MRiganSUSX I did not include the APA count for the HD cold box because the file for the HD cold box contains the channels for 4 APAs. It was not clear to me that HD cold boxes are only 1 APA.

Changing the unused variable is outside the scope of this PR. I can submit another PR regarding this issue if needed.

**Comment by MRiganSUSX** [comment]
It's only possible to fit one APA in the coldbox, but perhaps it could have been any one over multiple coldbox runs.
I think that's fair re the warning, just wanted to mention it as I noticed it while building for this review.

**Review by MRiganSUSX — APPROVED** [review]
otherwise lgtm

**Pull request merged**
